### ISSUE TITLE
Incorrect python parsing

### ISSUE THREAD

**Issue by shchemelevev** [preservim/tagbar#209]
For this python code:

```
    mortgage_monthlypayment_max = models.DecimalField(
        u'Максимальная сумма платежа (ипотека)',
        default=0,
        max_digits=20,
        decimal_places=2,
    )
    mortgage_rate_min = models.DecimalField(
```

will be shown following tags:

```
mortgage_monthlypayment_max
default
max_digits
decimal_places
```

**Comment by Xepe** [comment]
Hello, 
Is there a solution for this behavior ? 
Thanks

**Comment by marojenka** [comment]
@Xepe hi.
There is nothing tagbar can do about it since it's ctag problem.
Good news is switching to [https://github.com/universal-ctags/ctags](universal-ctags) will solve that problem.

@majutsushi it would be nice to drop a note in package description that universal-ctags not only recommended but solve this problem with python code. (may be not)
cheers.
