### ISSUE TITLE
tagbar can't recognize the method after  occurring three quotes string in python

### ISSUE THREAD

**Issue by junmoxiao** [preservim/tagbar#418]
![1111111111](https://cloud.githubusercontent.com/assets/9711902/25908780/adce6ac2-35dd-11e7-9a68-ba91571086a4.png)

the self.banner is in __init__ method ,and it's value is a three quotes string,
but the tagbar think the later method is not belong to this class

**Comment by majutsushi** [comment]
This looks like an issue with the ctags parser to me. Please run ctags manually as explained in `:h tagbar-issues` to check whether the output is correct.

Are you using Exuberant Ctags or Universal Ctags? If you're not using Universal Ctags I would recommend switching to that. If it still happens with that then I would recommend opening an issue on their bugtracker.

**Comment by raven42** [comment]
@junmoxiao Can you confirm if this issue still exists? It looks like it might be an issue with Exuberant Ctags which doesn't have as much support as Universal Ctags. If using Universal Ctags does address this, we can close out this issue. Otherwise can you please include a code snippet that reproduces this issue with Universal Ctags? A screenshot is helpful for showing what you are seeing, but to reproduce an actual code sample would be needed.

**Comment by junmoxiao** [comment]
@raven42 
problem is solved.
the code snippet is from here 
```
https://github.com/threat9/routersploit/blob/master/routersploit/interpreter.py
```
![image](https://user-images.githubusercontent.com/9711902/98325218-3d5a2d00-2029-11eb-95c6-60f592b0d7bd.png)

**Comment by raven42** [comment]
Thanks. Closing this issue.
