### ISSUE TITLE
Can't show function signature for Python

### ISSUE THREAD

**Issue by holybreath** [preservim/tagbar#50]
when open tagbar, only show the function name, none (params). 
but i guess this function should be there.
Did I missed something? or this function need python.dll ?

**Comment by eshansingh** [comment]
Hey @majutsushi, this issue seems to have become relevant again. On macOS 10.12.1 with Neovim, function signatures for Python don't seem to be showing up. But here too, pressing space shows the line correctly. Could this be an issue on my end? I tried using the ctags output alone as described in `tagbar-issues`, but I really couldn't notice anything special about it.

**Comment by majutsushi** [comment]
As far as I can see nothing should have really changed here, it's working fine for me with both Exuberant Ctags and Universal Ctags. Neovim shouldn't make a difference there, and I've tried it with that as well. My only guess would be that you're using the latest release of Exuberant Ctags instead of the development version.

The display when showing space is generated differently and is not really applicable for the normal Tagbar window, it just happens to look similar for Python.

**Comment by eshansingh** [comment]
@majutsushi You're right, that was indeed the issue. Thanks a lot for your time!
