### ISSUE TITLE
auto-toggle tagbar on window size

### ISSUE THREAD

**Issue by AdrienLemaire** [preservim/tagbar#512]
I thought this would be a rather common question, but couldn't find any related issue.

I'm used to working with vim within tmux, so my panes are usually small. I have the habit to toggle the pane to full screen with the tmux shortcut ctrl-b-z.

What I would like to do is:
* When in full screen (or better when in a pane which width is larger than 90 chars/cols), I want tagbar to auto-open itself
* When in panes which width < 90 chars, I'd like tagbar to auto-close itself.

Having to manually press F8 all the time is annoying and unproductive. Do you have a good trick to handle this ?

**Comment by Fandekasp** [comment]
@majutsushi I added the following conf:

```
augroup TAG
    autocmd VimEnter * nested if &columns >= 90 | TagbarOpen | wincmd p | endif
    autocmd VimResized * nested if &columns >= 90 | TagbarOpen | wincmd p | else | TagbarClose | endif
augroup END
```

When there is no tagbar open and I make my vim window larger, it auto-appears as expected. But when I resize my vim window under 90 columns, the TagbarClose function isn't executed or fail silently. The tagbar persists when I want it to disappear. Any idea why ?

**Comment by alerque** [comment]
I don't think doing things automagically like this is very common in the VIM world, at least not for a plugin to do so out of the box. Most of us tend to want our editor to do exactly what we ask for, no more no less. Hence I don't think a configuration like this will ever make it into the default.

That being said I would be happy to see you or somebody figured out a configuration that does work consistently, and when you do I'd love to see that contributed as an optional extra configuration and documented so that others who do want such a thing are able to do so!

**Comment by AdrienLemaire** [comment]
Realizing that I actually rarely use nor need Tagbar now that I'm comfortable with vim's internal file fuzzy finder.
Thanks for the comment though!

**Comment by alerque** [comment]
Personally I never use `tagbar` for navigating at all, I use `Clap`'s fuzzy grep to jump to things, but I do use this as a visual overview of what's in a file so I know what I can even search for ;-)

**Comment by raven42** [comment]
@AdrienLemaire would something like the following in your `.vimrc` work for this need?

```vim
if winwidth(0) > 90
    silent TagbarOpen
endif
```

Also as per your last comment, it sounds like you may not need this anymore. If not, we can probably close out this issue.
