### ISSUE TITLE
 Universal Ctags (still) doesn't generate tags for html

### ISSUE THREAD

**Issue by nerdfiles** [preservim/tagbar#627]
Was closed. Sorry to bump in this way, but no explanation was given as to why it was closed. 

See: https://github.com/majutsushi/tagbar/issues/317#issuecomment-655578674

**Comment by alerque** [comment]
The other issue was closed before `uctags` generated anything at all (and it was explained). Since there is upstream support now I'd be happy to include default configs, but somebody has to come up with a tag map so we know what to display. I'm happy to accept a PR, but I don't work with HTML much so somebody else should have a go. Please feel free yourself @nerdfiles...

**Comment by alerque** [comment]
Code that likely fixes this has been [dropped in a comment on that related issue](https://github.com/preservim/tagbar/issues/716#issuecomment-738907776), if anybody wants to make a PR out of it that would be great.

**Comment by prizelk** [comment]
> Code that likely fixes this has been [dropped in a comment on that related issue](https://github.com/preservim/tagbar/issues/716#issuecomment-738907776), if anybody wants to make a PR out of it that would be great.

Made a PR with raven42's working code #763.
