### ISSUE TITLE
Parameters not appearing on new line

### ISSUE THREAD

**Issue by mtshrmn** [preservim/tagbar#647]
First of all, thanks for this great plugin.

I feel like I'm doing something wrong. Here's a screenshot of what's the problem
![image](https://user-images.githubusercontent.com/18540571/91032999-66af1380-e60b-11ea-9b09-baf4094c1030.png)

The parameters of each method aren't on a new line and are being cut off at the end. For the life of me, I can't find anywhere info on what to do. Please help me.

The stuff I've done:
1. downloaded [ctags](https://www.archlinux.org/packages/extra/x86_64/ctags/) for arch.
2. added the plugin in vimrc using vundle. 
3. tried [universal-ctags-git](https://aur.archlinux.org/packages/universal-ctags-git/) instead, hoping it would solve the problem

**Comment by alerque** [comment]
To my knowledge Tagbar does not support multi-line display, each entry is drawn on a single line. Did you see something that led you to believe otherwise? I could be wrong. A multi-line output format would be a useful feature to add as a configurable option. If somebody wants to tackle it I'd be happy to help with review and merging.

**Comment by wsdjeg** [comment]
@alerque @mtshrmn do you try to enable `wrap` option in tagbar buffer, just run `set wrap` in tagbar windows. and if it works for you , you can use `autocmd Filetype tagbar setlocal wrap` in your vimrc.

**Comment by raven42** [comment]
@wsdjeg I pushed a potential solution up for this, you can try #659 out as an option to address this issue.
