### ISSUE TITLE
tagbar issue cleanup

### ISSUE THREAD

**Issue by raven42** [preservim/tagbar#679]
Opening this up to any tagbar contributor and issue reporters.

There are currently 106 open issues against tagbar, and some of them are quite old and haven't been updated in a very long time. If everyone is fine with it, I'd like to begin the effort of cleaning up any old issues that haven't been updated in years. I would propose that we can go through any issues that haven't seen any updates in over a year and if there hasn't been a confirmed bug, then we can either just close them out, or we can post a question to the issue asking if the issue is still seen.

Does anyone have any input on this?

**Comment by alerque** [comment]
When I started maintaining this I made it through about 100 old issues. The 100 or so that are left are what I didn't make it through. It's pretty time consuming to read and decipher old issues, then confirm whether there is still something there or not. I found at least half of the issues I worked on really were still legitimate issues and about half had already been fixed or people were just doing something wrong.

Old issues where anybody has responded asking for clarification or whatever and the OP has dropped it can probably be dismissed after a cursory check. This is easily half of the ones that are left.

Another small chunk are for platforms (e.g. Windows) or languages that I just have no way to check and hence glossed over.

I don't think we should close issues without making *some* attempt to confirm them. I hate it when old issues of mine –even 5 year old ones– get summarily closed just because some maintainer didn't bother trying to verify them when I know full well they are still issues. We should at least try. If we either try to replicate and fail or there isn't enough information to even try then at least a comment asking for further details should precede closure by at least a few couple week margin.

But yes! Issue cleanup is a great thing. Eventually the goal would be to only have actionable issues left open.

**Comment by alerque** [comment]
And for anybody out there reading this ... you don't have to be a current maintainer to contribute to issue triage! If you know a little VIM feel free to dig into the issue list and try to figure out what the issues are about. If you can replicate the issue, comment and say so. If you can't, comment and say so. If it needs details, comment and ask for them.

If I see people contributing quality comments on the issue tracker that further issues besides just their own I'll jump in and confer privs so you can do things like adjust labels and close issues as well.

**Comment by raven42** [comment]
Will work through the issues on a case by case basis where appropriate. Closing this one out.

**Comment by alerque** [comment]
You just wanted the open issue count to dip below 100! It's okay, I feel you — carry on.

**Comment by raven42** [comment]
Heh heh... yup... just trying to make some progress on the backlog.
