### ISSUE TITLE
question: tab names becomes __tagbar__.* when cursor is in the tagbar window

### ISSUE THREAD

**Issue by ssh352** [preservim/tagbar#690]
Is it possible for vim to show the source file name instead of  `__tagbar__.*`

? 

When I have multiple tabs open and if the cursor is in the tagbar window. Vim will be like this:
<img width="1483" alt="Screen Shot 2020-10-29 at 10 41 46 AM" src="https://user-images.githubusercontent.com/41779116/97518978-5c2a4500-19d3-11eb-83fc-26410c2974ef.png">

So I lose the visual clue which tab has which source file. It makes switching to a specific tab more difficult.

**Comment by alerque** [comment]
What tab UI are you using here? I'm using airline and get something different. The panes are well labeled:

![image](https://user-images.githubusercontent.com/173595/97553318-5722c100-19e6-11eb-8945-9580d80693d1.png)

I do see the *buffer* name header has the name you display, but that seems correct to me.

**Comment by ssh352** [comment]
I uses lightline. yeah I believe it is not tag bar's fault. It is displaying the buffer name correctly as `__tagbar__.*`.  It is just a bit inconvenient if I have multiple tabs open and some of them appears as  `__tagbar__.*`.

**Comment by raven42** [comment]
Unfortunately we can't really change the name of the tagbar buffer easily. The buffer name is how the tagbar plugin code finds the correct window/buffer so it can update itself.

Also, I would recommend against using tabs. Vim doesn't handle the tabs and buffers quite the way one would want. Specifically with regard to the same file. Say you have the following files open in tabs:
```
Tab 1:
    File A - Buffer 1
    File B - Buffer 2
    Tagbar - Buffer 3
Tab 2:
    File C - Buffer 4
    Tagbar - Buffer 5
```
Now say you are currently looking at File C and want to use your ctags with `CTRL-]` to jump to a tag in File A. The behavior you would want is for Vim to jump to Tab 1 and activate Buffer 1 for File A. Instead it is going to open up File A in a new buffer in Tab 2 and you'll be left with this:
```
Tab 1:
    File A - Buffer 1
    File B - Buffer 2
    Tagbar - Buffer 3
Tab 2:
    File C - Buffer 4
    Tagbar - Buffer 5
    File A - Buffer 6
```
As you can see this becomes problematic and now any changes you make in Buffer 1 aren't going to be reflected in Buffer 6 until you save any changes in Buffer 1 and then reload Buffer 6. There is also more info you can read about [here](https://stackoverflow.com/questions/19472029/how-to-have-different-title-and-tab-title-in-vim)

Instead since you are using lightline, I'd recommend using [Lightline-Bufferline](https://github.com/mengelbrecht/lightline-bufferline) which gives the same visual look, but works all within the same tab and then you can also provide a callback function to handle the buffer naming. The only drawback is with vim you can't click on the buffer names with the mouse to switch to that buffer. However I find that using keyboard shortcuts removes the need for that.

I have this setup pretty similar in my [.vimrc](https://github.com/raven42/dotfiles/blob/master/.vimrc) if you want to take a look. The relevant sections are the [Lightline#Bufferline Configuration](https://github.com/raven42/dotfiles/blob/78a43a9c7033307c8060ac526934af737d6afc54/.vimrc#L469) and then there are shortcuts for handling buffer switching using the [BufAcivate](https://github.com/raven42/dotfiles/blob/78a43a9c7033307c8060ac526934af737d6afc54/.vimrc#L774) routines.

All that said, if you are still wanting to use tabs, I think you will have to look into `:h setting-tabline` for info about setting the tabline labels. In the callback you could loop through all buffers in that tab to find the last buffer that is not `__Tagbar__.*` or even other buffers if you want to ignore them.

**Comment by ssh352** [comment]
@raven42 Thank you for the gracious explanation!

**Comment by raven42** [comment]
You're most welcome. Does this address all your concerns with this?

**Comment by ssh352** [comment]
Yes. closing the issue.
