### ISSUE TITLE
How do you view tags of another file?

### ISSUE THREAD

**Issue by joshpetit** [preservim/tagbar#691]
Would it be possible to open up the tags of another file? For example, if I were to have two java classes, open the tags of the second inside of the first so that I can have it as a reference.

**Comment by alerque** [comment]
Tagbar doesn't easily support anything other than being a sidebar for the current buffer. It *could* be hacked such that you manually open your own tagbar generated pane connected to a different buffer, but it's going to require some contortions on your part. Off the top of my head I don't know what that code to instantiate that is going to be exactly.

There are other plugins that work with tags at a project level rather than file level.

**Comment by joshpetit** [comment]
Ok that makes sense, 
> There are other plugins that work with tags at a project level rather than file level.

could you recommend a plugin that works on the project level? That would be great!

**Comment by alerque** [comment]
I think [vista](https://github.com/liuchengxu/vista.vim) might do that, and a quick search suggests [taglist](https://github.com/yegappan/taglist) does. I'm sure there are others.

**Comment by joshpetit** [comment]
Thanks a lot, these plugins save a lot of time! I'll make sure to check both of them out.
