### ISSUE TITLE
Goes to minimap instead of code on enter

### ISSUE THREAD

**Issue by 12-Seconds** [preservim/tagbar#700]
I'm using [minimap.vim](https://github.com/wfxr/minimap.vim), and when I press enter in tagbar, instead of going to the function in the code, it goes to an open minimap.vim window.

## Gif:

![output](https://user-images.githubusercontent.com/59331191/97800713-ea5f2f00-1c50-11eb-8218-c691e0d5abb1.gif)

**Comment by raven42** [comment]
It looks like this is occurring because of window/buffer switching that is happens both in tagbar and minimap when the active buffer changes. In both plugins, they update their own windows when the active buffer changes. So they read in the file data for the active buffer, then switch to themselves, then redraw themselves, and switch back to the previous buffer. So what you are seeing here is a side effect of that buffer switching.

Fortunately it looks like this is an easy fix (at least it was when I tried it). You can update the minimap configuration to ignore the tagbar window. I added the following to my .vimrc and the tagbar jumps are all working as expected now.

```vim
let g:minimap_block_filetypes = ['fugitive', 'nerdtree', 'tagbar']
```

The `'fugitive'` and `'nerdtree'` entries are in the default list in the minimap plugin. So adding `'tagbar'` to the list did the trick for me.

**Comment by 12-Seconds** [comment]
The minimap configuration worked for me. Thanks.

**Comment by alerque** [comment]
I've submitted that change as a PR to minimap.

**Comment by alerque** [comment]
@12-Seconds This fix was merged into minimap defaults so you should be able to drop your custom config again.

**Comment by 12-Seconds** [comment]
@alerque It works without the custom config, thanks!
