### ISSUE TITLE
Hide anonymous functions.

### ISSUE THREAD

**Issue by matheusfillipe** [preservim/tagbar#726]
On C++ is there any way to ignore the anonymous functions on tagbar? 

![image](https://user-images.githubusercontent.com/24435787/103491048-150b6680-4dff-11eb-8c92-3749df251f93.png)

I am using a lot of those and is hard to keep track this way 😅 I couldn't find how to do this yet or any related issue.

**Comment by raven42** [comment]
There is no tagbar option to suppress the anonymous tags that ctags generates. And to my knowledge there is on option for ctags to disable the anonymous tags either. It could be possible to override the default ctags options to use `--extras=` instead of `--extras=+F`, but that will only change the ctags output to no longer include any file scoped variables. So if all your tags in a file were not file scope except the anonymous ones, that might work for you. But that is a more specialized case.

It might be possible to update the tagbar code to ignore any anonymous tags via a new option. However this would pose a problem when a tag is a member of an anonymous parent. Consider for example the following code using an anonymous namespace in c++:
```c++
namespace
{
	class SomeClass
	{
		public:
			void SomeFunction() {}
	};

	void AnotherFunction() {}
}
```

For this, ctags will generate the following tags:
```
__anonfcd100560111	test.cpp	/^{$/;"	n	line:4	file:	end:12
SomeClass	test.cpp	/^	class SomeClass$/;"	c	line:5	namespace:__anonfcd100560111	file:	end:9
SomeFunction	test.cpp	/^			void SomeFunction() {}$/;"	f	line:8	class:__anonfcd100560111::SomeClass	typeref:typename:void	file:access:public	signature:()	end:8
AnotherFunction	test.cpp	/^	void AnotherFunction() {}$/;"	f	line:11	namespace:__anonfcd100560111	typeref:typename:void	signature:()	end:11
```

Of specific note, the `SomeClass` and `SomeFunction` tags reference the anonymous namespace. So the tagbar code will normally create a hierarchy like this:
```
__anonfcd100560111
    SomeClass : class
        SomeFunction() : void
    AnotherFunction() : void
```

If the anonymous tags are ignored, then we would have child tags that have a missing parent and so the rendering of the tagbar window will likely fail. Any child tags that are inside of that anonymous tag will not be visible. However if you want to try it out to see if it will work for your needs, you can try this patch:
```diff
diff --git a/autoload/tagbar.vim b/autoload/tagbar.vim
index 4aaf9a4..5d6fec8 100644
--- a/autoload/tagbar.vim
+++ b/autoload/tagbar.vim
@@ -1281,6 +1281,11 @@ function! s:ProcessFile(fname, ftype) abort
         if line =~# '^!_TAG_' || has_key(seen, line)
             continue
         endif
+        if g:tagbar_ignore_anonymous && line =~# '__anon'
+            call tagbar#debug#log('anonymous tag found - ignoring per tagbar configuration')
+            continue
+        endif
+
         let seen[line] = 1
 
         let parts = split(line, ';"')
diff --git a/doc/tagbar.txt b/doc/tagbar.txt
index 7e809ae..07ae749 100644
--- a/doc/tagbar.txt
+++ b/doc/tagbar.txt
@@ -1136,6 +1136,17 @@ highlight the 'SOME_MACRO' tag.
 Example: >
         let g:tagbar_highlight_method = 'nearest'
 <
+                                                    *g:tagbar_ignore_anonymous*
+g:tagbar_ignore_anonymous~
+Default: 0
+
+If set, any '__anon' tags generated by ctags will be ignored and will not be
+displayed in the tagbar window. Note: this will also mean any child tags of
+that anonymous tag will also not be visible.
+
+Example: >
+    let g:tagbar_ignore_anonymous = 1
+<
 
 ------------------------------------------------------------------------------
 HIGHLIGHT COLOURS                                           *tagbar-highlight*
diff --git a/plugin/tagbar.vim b/plugin/tagbar.vim
index 9c401fe..75c1a00 100644
--- a/plugin/tagbar.vim
+++ b/plugin/tagbar.vim
@@ -101,6 +101,7 @@ function! s:setup_options() abort
         \ ['left', 0],
         \ ['help_visibility', 0],
         \ ['highlight_method', 'nearest-stl'],
+        \ ['ignore_anonymous', 0],
         \ ['position', default_pos],
         \ ['previewwin_pos', previewwin_pos],
         \ ['scopestrs', {}],
```

**Comment by matheusfillipe** [comment]
The patch worked wonderfully in my case where I had no parent anonymous functions:
![image](https://user-images.githubusercontent.com/24435787/103575147-016c0880-4eb0-11eb-9c97-62f34afb2244.png)

On your example, it worked as expected I suppose? Looks fine to me.
![image](https://user-images.githubusercontent.com/24435787/103575430-7e977d80-4eb0-11eb-8977-da4805b5d98a.png)

I think this is a nice feature for javascript too, so yeah, definitely should be added.
