### ISSUE TITLE
Consider releasing a new git tag

### ISSUE THREAD

**Issue by anthraxx** [preservim/tagbar#841]
Hi, it would be great if we could push git tags frequently. This would help picking up all the great work for users that prefer running from tags or use distro shipped packages. The last tag is from Jan 21, 2021.

Thanks a lot :cat:

**Comment by alerque** [comment]
https://github.com/preservim/tagbar/releases/tag/v3.1.0

**Comment by alerque** [comment]
Ya so ... I used two terminals during the release process and it turns out one of them was on a different repo. I tagged from the one that was behind master not the one I pulled on, oops.

[v3.1.1](https://github.com/preservim/tagbar/releases/tag/v3.1.1) should reflect the actual current HEAD at this time and since it has been sitting for a month or so at 83933d5 should be a decent checkpoint to use. Sorry about the noise.
